version: "3.7"

networks:
  traefik_homenet:
    external:
      name: traefik_homenet

volumes:
  shared_data:
    external:
      name: shared_data

services:
  hydra:
    image: "linuxserver/hydra"
    container_name: "nzbhydra"
    volumes:
      - ${USERDIR}/data/nzbhydra:/config
      - ${USERDIR}/Downloads:/downloads
      - shared_data:/shared
    ports:
      - "5075:5075"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_homenet
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nzbhydra"
      - "traefik.frontend.rule=Host:nzbhydra.${DOMAINNAME}"
      - "traefik.port=5075"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_homenet"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
