version: "3.7"

networks:
  traefik_homenet:
    external:
      name: traefik_homenet

volumes:
  plex_data:
    external:
      name: plex_data
  shared_data:
    external:
      name: shared_data

services:
  plex:
    container_name: plex
    restart: always
    image: plexinc/pms-docker
    volumes:
      - ${USERDIR}/data/plex/config:/config
      - ${USERDIR}/data/plex/transcode:/transcode
      - plex_data:/data
      - shared_data:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-N6ccGYSzVmaeQy7qox9i"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP=http://${SERVERIP}:32400,https://plex.${DOMAINNAME}:443
    networks:
      - traefik_homenet
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:plex.${DOMAINNAME}"
      - "traefik.port=32400"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_homenet"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
