version: "3.7"

networks:
  traefik_homenet:
    external:
      name: traefik_homenet

services:
  traefik:
    hostname: traefik
    image: traefik
    container_name: traefik
    domainname: ${DOMAINNAME}
    restart: always
    networks:
      - traefik_homenet
    ports:
      - 443:443
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config/:/etc/traefik/
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      traefik.enable: true
      traefik.domain: "${DOMAINNAME}"
      traefik.tags: web,lb,traefik
      traefik.port: 8080
      traefik.backend: traefik
      traefik.frontend.rule: "Host:traefik.${DOMAINNAME}"
      traefik.frontend.auth.basic.users: "${HTTP_USERNAME}:${HTTP_PASSWORD}"
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.browserXSSFilter: true
      traefik.frontend.headers.contentTypeNosniff: true
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.SSLHost: "${DOMAINNAME}"
      traefik.frontend.headers.STSIncludeSubdomains: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.frameDeny: true
      traefik.docker.network: "traefik_homenet"
    command:
      - '--configFile=/etc/traefik/traefik.toml \'
