version: "3.7"

networks:
  homenet:

services:
  traefik:
    image: traefik
    restart: always
    networks:
      - homenet
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config/:/etc/traefik/
    labels:
      traefik.enable: true
      traefik.domain: "fqdn.com"
      traefik.tags: web,lb,traefik
      traefik.frontend.rule: "Host:traefik.docker.localhost"
      traefik.docker.network: "homenet"
    command:
      - '--configFile=/etc/traefik/traefik.toml \'
      - "--logLevel=DEBUG"
