# Set default entrypoints
defaultEntryPoints = ["http", "https"]

checkNewVersion = true
MaxIdleConnsPerHost = 500
logLevel = "INFO"
sendAnonymousUsage = true

# Launch API
[api]

# Connect to Docker host to get the running docker instances
[docker]
  domain = "docker.localhost"
  watch = true
  exposedByDefault = false

# Additional static configuration file
[file]
  filename = "/etc/traefik/rules.toml"
  watch = true

# TLS Let's Encrypt configuration with Cloudflare support
[acme]
email = "my@email"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true
acmeLogging = true
  [acme.DNSChallenge]
  provider = "cloudflare"

# Request wildcard domain TLS
[[acme.domains]]
  main = "*.fqdn.com"

# Run on those ports
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]