#debug = false
logLevel = "INFO"
InsecureSkipVerify = true 

# Set default entrypoints
defaultEntryPoints = ["https"]

checkNewVersion = true
MaxIdleConnsPerHost = 500
sendAnonymousUsage = true

# Launch API
[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"

# Connect to Docker host to get the running docker instances
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "phanee.tk"
  watch = true
  exposedByDefault = false

# Additional static configuration file
[file]
  filename = "/etc/traefik/rules.toml"
  watch = true

# TLS Let's Encrypt configuration with Cloudflare support
[acme]
email = "my@email"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true
acmeLogging = true
onDemand = false #create certificate when container is created
[acme.DNSChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 300
[[acme.domains]]
  main = "phanee.tk"
# Request wildcard domain TLS
[[acme.domains]]
  main = "*.phanee.tk"

# Run on those ports
# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoint.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]