FROM openjdk:8-jre-alpine

MAINTAINER Phaneendra <phaneendra@gmail.com>

ARG http_proxy=""
ARG https_proxy=""
ARG proxy_auth=""

ENV WILDFLY_VERSION 10.1.0.Final
ENV JBOSS_HOME /opt/jboss/wildfly
ENV STANDALONE standalone

ENV http_proxy $http_proxy
ENV https_proxy $https_proxy
ENV HTTP_PROXY_AUTH $proxy_auth

RUN echo env

USER root
RUN mkdir -p /opt/jboss \
    && adduser -D -h /opt/jboss jboss \
    && apk update \
    && apk add curl \
    && rm -rf /var/cache/apk/*

USER jboss
WORKDIR /opt/jboss
RUN curl -O http://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.zip && unzip wildfly-$WILDFLY_VERSION.zip && mv $HOME/wildfly-$WILDFLY_VERSION $HOME/wildfly && rm wildfly-$WILDFLY_VERSION.zip

ADD ./standalone/configuration/standalone.xml $HOME/wildfly/standalone/configuration/standalone.xml

EXPOSE 8080 9990
CMD /opt/jboss/wildfly/bin/standalone.sh --server-config=$STANDALONE.xml -b 0.0.0.0