version: "3.7"

networks:
  traefik_homenet:
    external:
      name: traefik_homenet

volumes:
  shared_data:
    external:
      name: shared_data

services:
  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./config:/etc/nginx/
      - ${USERDIR}/data/www:/var/www/${DOMAINNAME}/public:ro
    ports:
      - "8081"
    environment:
      - NGINX_HOST=www.${DOMAINNAME}
      - NGINX_PORT=8081
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_homenet
    command: [nginx, "-g", "daemon off;"]
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:www.${DOMAINNAME}"
      - "traefik.port=8081"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_homenet"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
